[package]
name = "simulation_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.6"
eframe = "0.26.2"
serialport = "4.3.0"
bevy = "0.13.0"
bevy_egui = "0.25.0"
bluetooth-serial-port = "0.6.0"